project:
  type: website
  output-dir: docs

website:
  description: "A blog built with Quarto"
  site-url: https://sa.mwel.ch # you must change this appropriately for RSS feeds to work properly
  title: "Sam Welch's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/samawelch/saw-quarto-blog/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



